# Compose file version
version: '3'
services:
  unite1: 
    # Build dockerfile in folder automate
    build: ./production-unite 
    # Echo command writing in the script.sh file launched by our crontab
    command: /bin/echo "/usr/local/bin/python3 /usr/src/devops-project-prod/main.py 1 10 >> /var/log/cron.log 2>&1" >> script.sh
    ports:
      - "3000:3000"

  unite2: 
    build: ./production-unite
    command: /bin/echo "/usr/local/bin/python3 /usr/src/devops-project-prod/main.py 2 10 >> /var/log/cron.log 2>&1" >> script.sh
    ports:
      - "3001:3001"

  unite3: 
    build: ./production-unite
    command: /bin/echo "/usr/local/bin/python3 /usr/src/devops-project-prod/main.py 3 10 >> /var/log/cron.log 2>&1" >> script.sh
    ports:
      - "3002:3002"

  unite4: 
    build: ./production-unite
    command: /bin/echo "/usr/local/bin/python3 /usr/src/devops-project-prod/main.py 4 10 >> /var/log/cron.log 2>&1" >> script.sh
    ports:
      - "3003:3003"

  unite5: 
    build: ./production-unite
    command: /bin/echo "/usr/local/bin/python3 /usr/src/devops-project-prod/main.py 5 10 >> /var/log/cron.log 2>&1" >> script.sh
    ports:
      - "3004:3004"

  database:
    build: ./bdd
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=false"
      - "MYSQL_ROOT_PASSWORD=test"

  # website:
  #   build: ./website
  #   ports:
  #     - "80:80"
